const tarotCards=["愚者","魔術師","女祭司","皇后","皇帝","教皇","戀人","戰車","力量","隱者","命運之輪","正義","倒吊人","死神","節制","惡魔","高塔","星星","月亮","太陽","審判","世界"];
let mood=localStorage.getItem("innerootMood")||"";let journal=localStorage.getItem("innerootJournal")||"";let drawnCard=localStorage.getItem("innerootCard")||"";
const backdrop=document.getElementById("modalBackdrop"),modalContent=document.getElementById("modalContent"),closeModalButton=document.getElementById("closeModal"),toast=document.getElementById("toast");
function showToast(message){toast.textContent=message;toast.hidden=false;clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.hidden=true,1700)}
function openModal(html){modalContent.innerHTML=html;backdrop.hidden=false}function closeModal(){backdrop.hidden=true}
function drawCard(){drawnCard=tarotCards[Math.floor(Math.random()*tarotCards.length)];localStorage.setItem("innerootCard",drawnCard);openModal(`<p class="eyebrow">今日抽牌</p><h2 id="modalTitle">${drawnCard}</h2><p>先不要急著找牌義。第一眼，你留意到什麼？它令你想到哪一段關係、情緒或回憶？</p><button class="primary" id="drawAgain">再抽一張</button>`);document.getElementById("drawAgain").addEventListener("click",drawCard)}
function openJournal(){openModal(`<p class="eyebrow">潛意識日記</p><h2 id="modalTitle">寫下此刻的你</h2><textarea id="journalInput" placeholder="今天發生了什麼？你有什麼情緒、身體感覺或反覆出現的想法？">${journal}</textarea><button class="primary" id="saveJournal">儲存此頁</button>`);document.getElementById("saveJournal").addEventListener("click",()=>{journal=document.getElementById("journalInput").value.trim();localStorage.setItem("innerootJournal",journal);closeModal();showToast("日記已儲存")})}
function makePrompt(){return `請不要把塔羅當作預測未來，而是作為自我探索與潛意識反思的工具。\n\n今天的心情：${mood||"未選擇"}\n今天抽到的牌：${drawnCard||"未抽牌"}\n我的記錄：${journal||"未填寫"}\n\n請從情緒、核心信念、重複模式、內在需要與身體感受角度，引導我理解自己。不要判定吉凶，請多用提問，最後提供一個今天可以實踐的小步驟。`}
async function copyPrompt(){const prompt=makePrompt();try{await navigator.clipboard.writeText(prompt);showToast("AI 探索指令已複製")}catch{openModal(`<p class="eyebrow">AI 探索指令</p><h2 id="modalTitle">長按以下內容複製</h2><textarea readonly>${prompt}</textarea>`)}}
function openMood(){openModal(`<p class="eyebrow">今日心情</p><h2 id="modalTitle">今天的你，感覺如何？</h2><div class="mood-list">${["很棒","平靜","普通","低落","焦慮"].map(item=>`<button data-select-mood="${item}">${item}</button>`).join("")}</div>`);document.querySelectorAll("[data-select-mood]").forEach(button=>button.addEventListener("click",()=>saveMood(button.dataset.selectMood)))}
function saveMood(value){mood=value;localStorage.setItem("innerootMood",mood);openModal(`<p class="eyebrow">已記錄</p><h2 id="modalTitle">今天的心情：${mood}</h2><p>記錄本身不是為了評價自己，而是慢慢看見情緒出現的規律。</p><button class="primary" id="finishMood">完成</button>`);document.getElementById("finishMood").addEventListener("click",closeModal)}
function openInsight(){openModal(`<p class="eyebrow">潛意識洞察</p><h2 id="modalTitle">從重複出現的情緒開始</h2><p>第一版會先記錄你的心情、牌卡和日記。之後再加入長期模式整理與每月回顧。</p><button class="primary" id="goJournal">寫一篇記錄</button>`);document.getElementById("goJournal").addEventListener("click",openJournal)}
function openGrowth(){openModal(`<p class="eyebrow">成長足跡</p><h2 id="modalTitle">你的森林正慢慢生長</h2><p>完成每日心情、抽牌或日記後，未來會在這裡形成你的探索時間線。</p><button class="primary" id="closeGrowth">返回首頁</button>`);document.getElementById("closeGrowth").addEventListener("click",closeModal)}
document.querySelectorAll("[data-action]").forEach(button=>button.addEventListener("click",()=>{const action=button.dataset.action;if(action==="home")window.scrollTo({top:0,behavior:"smooth"});if(action==="draw")drawCard();if(action==="journal")openJournal();if(action==="prompt")copyPrompt();if(action==="growth")openGrowth();if(action==="mood")openMood();if(action==="insight")openInsight()}));
document.querySelectorAll("[data-mood]").forEach(button=>button.addEventListener("click",()=>saveMood(button.dataset.mood)));closeModalButton.addEventListener("click",closeModal);backdrop.addEventListener("click",event=>{if(event.target===backdrop)closeModal()});document.addEventListener("keydown",event=>{if(event.key==="Escape")closeModal()});
